### ISSUE TITLE
Làm homepage:

### ISSUE THREAD

**Issue by hoangminhtuan1399** [chenjiinguyen/C4E-NHOM3DACK1#2]
- [x] Header
- [x] Slider
- [x] Gian hàng T-shirt
- [x] Gian hàng sweater
- [x] Gian hàng hoodie
- [x] Contact
- [x] Footer
- [x] Event Listener
@Nhom3-DuongMinhHieu

**Comment by Nhom3-DuongMinhHieu** [comment]
hôm nay thời tiết âm u làm cho tâm trạng bị u buồn quá nên thôi mai t làm nha =)))

**Comment by hoangminhtuan1399** [comment]
> hôm nay thời tiết âm u làm cho tâm trạng bị u buồn quá nên thôi mai t làm nha =)))

Miễn sao trước đét lai =))))
